### ISSUE TITLE
Sampling scheme VS measure for volume of neighborhood

### ISSUE THREAD

**Issue by emdann** [MarioniLab/milo#10]
Testing combinations of sampling scheme and measure for volume of neighbourhood (distance, edge connectivity ...)

**Comment by emdann** [comment]
Just saw this, soz. I really don't think it will matter, will it? And k-distance is top in terms of scalability anyway.

**Comment by MikeDMorgan** [comment]
Yeah, I don't think it matters - people can use them if they want to... maybe the reviewers might ask about it?

**Comment by emdann** [comment]
Do we even want to mention the different weighting schemes in the text?

**Comment by MikeDMorgan** [comment]
Nah - it's more just a feature of the package. We can maybe have a vignette that shows the different approaches, but I don't see people using the other methods as they are really quite slow in comparison.
