### ISSUE TITLE
Comparing Milo to other methods

### ISSUE THREAD

**Issue by MikeDMorgan** [MarioniLab/milo#12]
Compare against:

* a simple cluster then DA testing
* cydar defined in PC space
* DA seq (https://github.com/KlugerLab/DAseq/tree/master/R)

**Comment by emdann** [comment]
It was brought to my attention that if we want to say this is good for DA on trajectories, we should compare with using a GLM on pseudotime ordered cells (dpt and monocle?)

**Comment by MikeDMorgan** [comment]
Uhm, this is fine for a linear trajectory - but nigh on impossible if there are any bifurcations.

**Comment by emdann** [comment]
Yes, I agree. Maybe it suffices to address this in the text.

**Comment by jcmarioni** [comment]
In the text is fine I think.
---

John Marioni PhD
Research Group Leader, EMBL-EBI
Associate Faculty Member, WT Sanger Institute
Wellcome Genome Campus
CB10 1SD, UK

Senior Group Leader
CRUK Cambridge Institute
University of Cambridge
CB2 0RE, UK
