### ISSUE TITLE
Scalability analysis

### ISSUE THREAD

**Issue by emdann** [MarioniLab/milo#15]
No of cells VS runtime 
@MikeDMorgan on a humongous simulated dataset
@emdann on downscaled liver dataset

**Comment by MikeDMorgan** [comment]
The relationship looks very similar for the simulations up to and including 100K cells. We might need to have a proper think about how to improve the scalability, but for now I think it's generally OK. There will also be memory issues (it tends to fallover ~120-140K cells due to the distance calculations).

![Simulation_timing](https://user-images.githubusercontent.com/6473398/94177787-09b8ae80-fe92-11ea-90d2-fd0b0915732b.png)

**Comment by emdann** [comment]
I wonder if for now we can make the case that with that many cells you can sample less neighbourhoods?

**Comment by emdann** [comment]
But also why does the liver take ~ 5 minutes with 50k cells and the simulation takes almost 20 mins?

**Comment by MikeDMorgan** [comment]
> I wonder if for now we can make the case that with that many cells you can sample less neighbourhoods?

We definitely need to generate a plot of the number of cells that fall into neighbourhoods, or whether the nearest neighbour of a cell is in a neighbourhood Vs the proportion of sampled for different sized data sets.



> But also why does the liver take ~ 5 minutes with 50k cells and the simulation takes almost 20 mins?

I have a feeling this might be about connectivity in the graph. The liver data has a lot of disjoint sets of cells so there _might_ be fewer distance calculations, but this is just a hunch. I need to run the timings with different values of `k` and `d`.

**Comment by MikeDMorgan** [comment]
A further issue is that once I run it on ~160K cells it runs out of memory (usage balloons to ~200GB). I wouldn't be surprised if this is an issue with the distance calculations, so we might need to separate the graph building and distance calculations to alleviate this.

**Comment by MikeDMorgan** [comment]
@emdann An update on the scalability. It can now at least run on ~200k cells without running out of memory, but it takes nearly 2 hours.

![Simulation_timing](https://user-images.githubusercontent.com/6473398/95723137-b655a700-0c6c-11eb-83aa-47669bbc0c3b.png)

**Comment by jcmarioni** [comment]
I don’t think that’s catastrophic - 2h is not a lot in the big picture and the key thing is that it runs on a standard computer without running out of memory…

J

 
---

John Marioni PhD
Research Group Leader, EMBL-EBI
Associate Faculty Member, WT Sanger Institute
Wellcome Genome Campus
CB10 1SD, UK

Senior Group Leader
CRUK Cambridge Institute
University of Cambridge
CB2 0RE, UK

**Comment by emdann** [comment]
And this is without parallelizing right?

**Comment by MikeDMorgan** [comment]
Without parallelisation yes, and there are steps that are embarssingly parallelisable, so that shouldn't be a concern. What I haven't tested yet is how much memory it uses as I had to run this on the CI cluster - I requested 84GB to do this, but I can't extract the actual memory usage from the slurm job as the job history was flushed over the weekend. I'll run a separate memory profiling to get a more accurate number.

**Comment by jcmarioni** [comment]
Okay. That would be good to know as that may be more of a limitation for users in practice…

---

John Marioni PhD
Research Group Leader, EMBL-EBI
Associate Faculty Member, WT Sanger Institute
Wellcome Genome Campus
CB10 1SD, UK

Senior Group Leader
CRUK Cambridge Institute
University of Cambridge
CB2 0RE, UK

**Comment by MikeDMorgan** [comment]
Memory usage by the end of the workflow. This is slightly misleading as it not strictly the maximum amount of memory used.

![Simulation_memory](https://user-images.githubusercontent.com/6473398/95850249-7237d480-0d48-11eb-912e-6fe31c5a5158.png)

**Comment by MikeDMorgan** [comment]
So it seems that the memory footprint of the Milo workflow is quite low, and the plot above is accurate. All of this memory usage comes from the `calcNhoodsDistance` function. I haven't yet assessed the amount of memory used by the Milo object, but I think it is going to be quite low.

Total memory across all functions:
![Simulation_memory-TotalMem](https://user-images.githubusercontent.com/6473398/95963403-8f7baa00-0dff-11eb-9f7d-5ca732ba093a.png)

`buildGraph`:
![Simulation_memory-GraphBuilding](https://user-images.githubusercontent.com/6473398/95963276-60fdcf00-0dff-11eb-8ec7-9cf208ee4281.png)

`makeNhoods`:
![Simulation_memory-makeNhoods](https://user-images.githubusercontent.com/6473398/95963297-6824dd00-0dff-11eb-822f-9d62031a9b29.png)

`calcNhoodDistances`:
![Simulation_memory-CalcNhoodDistance](https://user-images.githubusercontent.com/6473398/95963321-74109f00-0dff-11eb-9c82-7a73653057e2.png)

`countCells`:
![Simulation_memory-countCells](https://user-images.githubusercontent.com/6473398/95963348-7bd04380-0dff-11eb-9813-9bdd00903d7c.png)

`testNhoods`:
![Simulation_memory-testNhoods](https://user-images.githubusercontent.com/6473398/95963370-84c11500-0dff-11eb-87e9-15d716ada6ce.png)

**Comment by emdann** [comment]
That's great!

**Comment by MikeDMorgan** [comment]
I'd like to take credit - but I think it's because we're building off the back of the `SingleCellExperiment` object - win!
